### ISSUE TITLE
Block Editor Settings: Unable to save settings

### ISSUE THREAD

**Issue by MarieComet** [DLXPlugins/highlight-and-share#66]
## What is the desired behavior?

Block Editor Settings are saved.

## What is the actual behavior?

Block Editor Settings aren't saved, returning "There are form validation errors. Please correct them above." but the form don't show any errors.

## Steps to reproduce undesired behavior:

1. Install the plugin
2. Visit the Block Editor Settings tab
3. Save Settings
4. Request return : 
`{"success":false,"data":[{"code":"has_adobe_fonts_error","message":"Could not connect to the Adobe Fonts API. The project ID may be incorrect."}]}`
But Enable Adobe Fonts is not active.

## Screenshots or Video
https://user-images.githubusercontent.com/7976501/223997367-9c331dc9-9ed1-4d84-a650-edc438d03c26.mov

## Additional Comments
Plugin version 4.1.1
WordPress version 6.1.1

Thanks for this great plugin.

**Comment by ronalfy** [comment]
Fixed with https://github.com/DLXPlugins/highlight-and-share/commit/6654500c4c8004f87f8360d3863e8b7a23a7d34c. Will be in the next release. Thank you.

**Comment by ronalfy** [comment]
Fixed in 4.2.1.
