### ISSUE TITLE
Feature Request - Scroll and Share

### ISSUE THREAD

**Issue by ronalfy** [DLXPlugins/highlight-and-share#73]
## Feature Request

What would you like to add or change in regards to Highlight and Share?

Have the approved social networks appear in resting state at the bottom of the screen after the user has scrolled to read the post.

Have it show up after the title has scrolled into view. Be in fixed position at the bottom of the screen. Disappear whenever scrolling, and reappear at resting state.

## Describe any solutions you've considered

Just having them displayed at the bottom of the post.

## How important is this feature to you?

It's way more obtrusive than I'd like it to be, but maybe that's the reason why this would be so effective.

## Is your feature request related to a problem? Please describe.

More use-cases for Highlight and Share.

## Additional context
Add any other context about the feature request here.

**Comment by ronalfy** [comment]
@hollyjahangiri 

From Chat GPT.

The Scroll to Share feature sounds like a promising addition to the Highlight and Share plugin. This feature could be implemented in a way that displays social sharing options when users scroll to a specific point on the page or after they have spent a certain amount of time on the page. Here are some ideas on how you can design the Scroll to Share feature:

Scroll-triggered sharing options: When a user scrolls down to a certain percentage of the page (e.g., 50% or 75%), the social sharing options will appear on the screen, encouraging them to share the content. You can make the sharing options appear as a floating sidebar, a bottom bar, or even as an unobtrusive pop-up.

Time-based sharing options: If a user spends a certain amount of time on the page (e.g., 30 seconds or 1 minute), the social sharing options will be displayed. This method assumes that users who spend more time on the page are more likely to be engaged with the content and therefore more likely to share it.

Content-based trigger: Display the sharing options when a user scrolls past a specific piece of content, like an important quote, a striking image, or an infographic. This approach encourages users to share content that resonates with them.

Customizable triggers: Allow users to choose between various triggering options (scroll percentage, time spent, or content-based) in the plugin settings. This customization ensures that the feature aligns with their preferences and the design of their website.

The Scroll to Share feature can further enhance user engagement on your website and promote social sharing. When implementing this feature, it's essential to ensure that the sharing options are not intrusive and do not disrupt the user experience. If you have any questions or need assistance with the development of this feature, please feel free to ask.

**Comment by ronalfy** [comment]
What can go on the pop-over.

Pop-overs are versatile and can be customized to include different sharing actions based on your preferences and target audience. When designing a sharing pop-over, it's essential to consider the user experience and the platforms most relevant to your content. Here are some common actions and options you can include:

Emailing the post URL: This option allows users to quickly share the post with their contacts via email. You can include an email icon or button within the pop-over, which opens the user's default email client with a pre-populated subject and body containing the post URL.

Web Share API: Utilizing the Web Share API enables users to share your content using the native sharing options on their devices. This feature provides a seamless experience and works well on mobile devices.

Expandable drawer for social networks: Instead of showing all social networks by default, you can include an expandable drawer or a "More options" button within the pop-over. When clicked, it will display a list of available social networks, allowing users to choose their preferred platform for sharing.

Show all social networks: If you prefer to display all social network icons within the pop-over, ensure that they are arranged in a visually appealing and organized manner. Limit the number of social networks to those that are most relevant to your target audience to avoid cluttering the pop-over.

Copy link option: Including a button to copy the post URL to the user's clipboard can be a useful addition, as it allows users to share the content on platforms not listed in the pop-over or through other communication methods.

Social network counters: Optionally, you can display the share count for each social network, giving users an idea of the post's popularity on different platforms.

When deciding which sharing actions to include in the pop-over, it's crucial to consider your audience and the type of content on your website. Prioritize the sharing options that are most relevant and useful to your users, and avoid overcrowding the pop-over with too many choices. If you have any questions or need assistance with designing the sharing pop-over, please feel free to ask.

**Comment by hollyjahangiri** [comment]
Time- and content-based triggers sound fairly unique.

Unobtrusive is critical.

**Comment by ronalfy** [comment]
I can't think of a non-dodgy way of doing this and I won't want to annoy people with my plugin. Marking as wontfix.
