### ISSUE TITLE
Feature Request - Add Web Share API Support

### ISSUE THREAD

**Issue by ronalfy** [DLXPlugins/highlight-and-share#76]
## Feature Request

The Web Share API provides a universal way for users to share content. It works with the existing device, not relying on a browser to share content.

Highlight and Share would have an option in advanced that would enable the Web Share API.

Technical docs: 

* https://developer.mozilla.org/en-US/docs/Web/API/Web_Share_API
* https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

On the frontend, when a user highlights text, clicks to highlight, or clicks to share, a Share button will be shown with an icon and an optional label.

Clicking on this icon will bring up the devices share settings.

With the Web Share API, you can share some text, a url, title. It can also share files, so this is an opportunity for future growth.

The Appearance settings screen will be adapted for the sharing API appearance.

I imagine we could customize:

1. The icon
2. Icon color
3. Icon color hover
4. Background
5. Background hover
6. Label
7. Label text color
8. Label text color hover

## Describe any solutions you've considered

We could keep Highlight and Share as-is and not need the extra bloat of this feature.

## How important is this feature to you?

It's a nice-to-have.

## Is your feature request related to a problem? Please describe.

The Web Share API allows for a lot more sharing options compared to what HAS offers.

**Comment by ronalfy** [comment]
@hollyjahangiri what do you think about this one?

**Comment by hollyjahangiri** [comment]
I think this sounds good, if I understand it correctly.
