### ISSUE TITLE
Facebook share (copy first, then paste into sharing box)

### ISSUE THREAD

**Issue by hollyjahangiri** [DLXPlugins/highlight-and-share#77]
Facebook share does not automatically take the highlighted text and add it to the text box. Couldn't Highlight and Share automatically Copy first, then Facebook share, then Paste clipboard text into the Facebook share dialog?

I can do this manually, but only if I remember to hit the copy icon first. 

I rarely use Twitter (deleted my personal account). I use Facebook often. It would be nice for Highlight and Share to truly share the highlight there.

**Comment by ronalfy** [comment]
Unfortunately not. Facebook makes sharing really difficult.

**Comment by hollyjahangiri** [comment]
You couldn't do it in the browser?

Ugh. Facebook.

**Comment by ronalfy** [comment]
Closing as Facebook doesn't support this.
